server:
  port: 23311

spring:
  application:
    name: service-verification-code

eureka:
  client:
    service-url:
      defaultZone: http://localhost:23300/eureka/,http://localhost:23301/eureka/,http://localhost:23302/eureka/
  instance:
    appname: ${spring.application.name}
    instance-id: ${spring.application.name}

info:
  app.name: ${spring.application.name}