server:
  port: 23333

spring:
  application:
    name: milet-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:23300/eureka/,http://localhost:23301/eureka/,http://localhost:23302/eureka/
  instance:
    instance-id: milet-zuul

#zuul:
#  routes:
#    passenger:
#      path: /passenger/**
#      serviceId: car-api
#    verificationCode:
#      path: /verificationCode/**
#      serviceId: service-verification-code
#  prefix: /api